[workspace]
authors = ["Max Rakitin <mrakitin@bnl.gov>, Jennefer Maldonado <jmaldonad@bnl.gov>"]
channels = ["conda-forge", "robostack-staging"]
name = "rclpy"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
topic-list = "ros2 topic list"
node-list = "ros2 node list"

[feature.ros.dependencies]
ipython = ">=9.9.0,<10"
ros-humble-rclpy = ">=3.3.16,<4"
ros-humble-ros2cli = ">=0.18.12,<0.19"
ros-humble-ros2topic = ">=0.18.12,<0.19"
ros-humble-ros2action = ">=0.18.12,<0.19"
ros-humble-ros2node = ">=0.18.12,<0.19"
ros-humble-turtlesim = ">=1.4.2,<2"

[feature.profile.dependencies]
bluesky-base = "==1.14.6"
matplotlib-base= ">=3.9.3,<4"
networkx = ">=3.4.2,<4"
nslsii = "==0.11.4"
numpy = "*"
ophyd = ">=1.11.0"
pyepics = "*"
python = "*"
semver = ">=3.0.4,<4"
tiled-client = ">=0.1.6"
lmfit = ">=1.3.4,<2"
paramiko = ">=4.0.0,<5"
peakutils = ">=1.3.5,<2"
suitcase-utils = ">=0.5.4,<0.6"
arvpyf = ">=0.4.3,<0.5"
telnetlib3 = ">=1.0.4,<2"
hdf5-external-filter-plugins = ">=0.1.0,<0.2"
databroker = "==2.0.0"
bluesky-tiled-plugins = ">=2.0.0b68"
#ophyd-async = ">=0.13.7,<0.14"

[feature.profile.pypi-dependencies]
pvxslibs = ">=1.3.2, <2"

[environments]
ros2 = {features=["profile", "ros"], solve-group="profile"}